### PR TITLE
Add no_data dsm option

### PR DESCRIPTION
**Pull request by alexgleith**
* Adds dsm_no_data option to Transforms
* Follows that dsm_no_data through to the dsm check
* Code cleanups

### CODE REVIEW

**Review by eloise-b — APPROVED** [review]
Looks good, and I see you've tidied up and reformatted some stuff! :)

**Comment by benjimin** [comment]
It would go good if any nodata values for the DSM were read directly from the DSM file metadata (noting there may be none, because there is an implied expectation that float rasters use NaN instead of a nodata value), via the nodata attribute of the xarray.

As an ODC principle, it should be possible to change what format a product is stored in the backend (including changing any nodata value in the stored rasters) without needing to update ODC applications (to correctly use the data).

**Comment by alexgleith** [comment]
Before:

image


After:

image

**Comment by alexgleith** [comment]
> It would good if any nodata values for the DSM were read directly from the DSM file metadata (noting there may be none, because there is an implied expectation that float rasters use NaN instead of a nodata value), via the nodata attribute of the xarray.
> 
> As an ODC principle, it should be possible to change what format a product is stored in the backend (including changing any nodata value in the stored rasters) without needing to update ODC applications downstream (to correctly use the data).

Thanks @benjimin. Note that the ODC metadata has nodata values specified explicitly, not implicitly. I think passing in a value is fine, especially since we know there are examples where the nodata value isn't set on the DEM.

**Pull request merged**
